# Generated by Django 2.1 on 2018-08-25 20:02

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of this media item', max_length=240)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(help_text='A tag for a media item', max_length=20), size=None)),
                ('ownership_status', models.CharField(choices=[('OWN', 'own'), ('WANT', 'want'), ('RSCH', 'research'), ('BRRW', 'borrowed'), ('STRM', 'streamed')], help_text='The ownership status of this item', max_length=4)),
                ('completion_status', models.CharField(choices=[('CMPT', 'completed'), ('INPG', 'in progress'), ('DRPD', 'dropped'), ('INQU', 'in queue')], help_text='The completion status of this item', max_length=4)),
                ('rating', models.IntegerField(default=-1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='MediaInformation',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='metadata', serialize=False, to='common.MediaItem')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
