# Generated by Django 2.1 on 2018-08-25 20:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaitem',
            name='rating',
            field=models.IntegerField(default=-1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(-1)]),
        ),
    ]
